### ISSUE TITLE
Doesn't extract msi installer of PDF-Xchange Editor properly

### ISSUE THREAD

**Issue by mzso** [Bioruebe/UniExtract2#69] opened 2017-05-29 09:12 UTC
Hi!

I've been using the Gora update of uniextract (with the unpacker suggested, by default: JSWare extraction) to extract those files. And it worked fine. It also works with the original if I use the option MsiX unpacker. But with UE2 I only got cab files and such useless things, not the program files.
link: https://www.tracker-software.com/product/pdf-xchange-editor/download?fileid=615

Curiously meanwhile testing with the same file the program started failing outright and not extracting anything. Weird...
Anyway I submitted a report.

**Comment by vatterspun** [comment] 2017-10-06 02:02
For those new to this topic, Gora was a developer who forked the project and made some welcome changes, but didn't share source code.  He evidently passed away in 2016.

There's a thread over on PFW about this: https://www.portablefreeware.com/forums/viewtopic.php?p=64405#p64405

**Comment by Bioruebe** [comment] 2019-01-09 08:07
The link you just added leads to PDF-XChange _Editor_. The title says PDF-XChange _Viewer_, so I tested [this installer](https://www.tracker-software.com/product/pdf-xchange-viewer/download?fileid=451), which extracted correctly.

However, I can confirm that the msi file you linked fails to extract.

**Comment by mzso** [comment] 2019-01-09 14:52
[**@Bioruebe**](https://github.com/Bioruebe) commented on [2019. jan. 9. 09:07 CET](https://github.com/Bioruebe/UniExtract2/issues/69#issuecomment-452606981 "2019-01-09T08:07:48Z - Replied by Github Reply Comments"):
> The link you just added leads to PDF-XChange _Editor_. The title says PDF-XChange _Viewer_, so I tested [this installer](https://www.tracker-software.com/product/pdf-xchange-viewer/download?fileid=451), which extracted correctly.
> 
> However, I can confirm that the msi file you linked fails to extract.

Apologies. I mistyped. (I used to use the old Viewer)

**Comment by Bioruebe** [comment] 2019-01-12 11:46
No problem, your report will bring some nice improvements to msi extraction :)

UniExtract now displays the method selector if the default extraction (lessmsi) fails. Then you can choose 'jsMSI Unpacker' and it works just like the older UniExtract versions/forks.
This still leaves some .cab files in the output directory, because lessmsi does not cleanup correctly after failing. (I would rather see it fixed in lessmsi than doing it in UE, so this will be resolved at a later time.)

**Closed by Bioruebe** 2019-01-12 11:46 UTC

**Comment by mzso** [comment] 2019-04-05 18:40
Hi!
I just used this the new V8 of the same app. The administrative packer now works.
(Note: I don't know if you're familiar with the Gora fork but it has two additional options for MSI: JSWare extraction, TC observer extraction. Those may be a little neater because they don't leave the useless .cab files around after extraction. (or the app doesn't))
