### ISSUE TITLE
Timeline: New release planned? When?

### ISSUE THREAD

**Issue by myfairsyer** [Bioruebe/UniExtract2#72] opened 2017-06-26 06:54 UTC
Reword it however you like, I'm just moving this to an own issue as in #70 @MelchiorGaspar told he didn't know where to put it. :)

So are there any further releases foreseeable?
Is there any plan?
Thanks

**Comment by MelchiorGaspar** [comment] 2017-06-26 06:57
ok...
"any chance you will be getting another beta out sooner or later?" - MelchiorGaspar

**Comment by DjDiabolik** [comment] 2017-06-26 11:08
To many users have make same question............ no answers.......... i thinks simply no.

**Comment by DjDiabolik** [comment] 2017-06-26 11:09
https://github.com/Bioruebe/UniExtract2/issues/45 it's a 3jan request...

**Comment by MelchiorGaspar** [comment] 2017-06-26 12:13
lol.. yeah go figure some one else already asked... ;) 
and IK asking for updates is not always the most popular question with devs ;p 
sry..  xD

**Comment by Bioruebe** [comment] 2017-07-05 06:19
> It's done, when it's done.

I didn't have much time lately to work on UniExtract, so sorry for the delays. It shouldn't take too long until the next update, but no promises here.

**Comment by MelchiorGaspar** [comment] 2017-07-05 06:59
no worry take your time thx for taking over and updating UniExtract..

**Comment by acook** [comment] 2017-07-05 19:07
This is basically a duplicate of #45.

More useful questions might be: 
- What are the blockers to making a new release?
- How to build the project yourself? What version of AutoIt is required? Anything else needed?

Maybe it'd be nice to include the build instructions in the README?

**Comment by vatterspun** [comment] 2017-07-06 01:41
@MelchiorGaspar 
> no worry take your time thx for taking over and updating UniExtract.

True.  A lot of forks of this project have come and gone and you've taken it a lot farther than any other.  We're lucky to have you.

**Comment by acook** [comment] 2017-07-06 03:57
If people are wondering how to build their own version, here is how:

0. Download [AutoIt](https://www.autoitscript.com/cgi-bin/getfile.pl?autoit3/autoit-v3.zip) and extract it to a folder (or install it if you got the installer)
1. Download [this repo](https://github.com/Bioruebe/UniExtract2/archive/master.zip) (use git or extract the zip to a folder)
2. Go your your AutoIt folder then into the Aut2exe folder and double click on `Aut2exe_64.exe`
3. Then browse to the folder you put the UniExtract2 source files and select `UniExtract2.au3`
4. Click `Compile`
5. Double click the `UniExtract2.exe` created by step 4

More info on AutoIt's website (with screenshots): https://www.autoitscript.com/autoit3/docs/intro/compiler.htm

**Comment by DjDiabolik** [comment] 2017-07-06 12:23
@acook and for all bin of extractor ?

**Comment by acook** [comment] 2017-07-06 20:22
@DjDiabolik Not sure what you mean? You can get all of the extractors with the last release?

**Comment by DjDiabolik** [comment] 2017-07-10 16:51
yeah... all external extractors...... how i can pick somethigs like an upgraded collection ?

**Comment by timofonic** [comment] 2017-07-10 18:23
@DjDiabolik 

Would you please make an upgraded pack? Please! :D

Does this fork features recursive scanning, renaming and extracting? It would be amazing!

**Comment by acook** [comment] 2017-07-12 14:29
Hmm. It does seem like it would be nice to have a script to download all of the extractors. If I have some time to look into that I will see what I can do. 

How should they be versioned?
1. Should we always try to grab the latest
2. or a specific version (in case a newer version breaks something)?

**Comment by jyrkive** [comment] 2017-07-24 06:57
I'd prefer always attempting to update to the latest version.

**Comment by MaDill** [comment] 2018-03-18 14:37
Is there any plan to download a new version without compile by my own?

**Closed** 2018-08-03 03:30 UTC

**Comment by DjDiabolik** [comment] 2018-08-05 13:29
thanks for rc 1...
