### ISSUE TITLE
Is RC1 complete? Compiled somewhere?

### ISSUE THREAD

**Issue by wcrlewis** [Bioruebe/UniExtract2#83] opened 2018-03-25 04:53 UTC
TIA

**Comment by d4k0** [comment] 2018-04-01 18:46
Hi,

I just compiled the latest version as I was also looking for it. You can find it here:

https://github.com/d4k0/UniExtract2/releases/tag/v2.0.0-rc.1-f208120

**Comment by mikhoul** [comment] 2018-04-02 17:38
Thanks @d4k0   :+1:

**Comment by wcrlewis** [comment] 2018-04-02 22:52
@d4k0  TY!

**Comment by thunderpants** [comment] 2018-04-03 01:09
wow ,one of my fav programs ,thanks for the new version!

**Comment by d4k0** [comment] 2018-04-29 22:31
I uploaded a new release with the latest changes:

https://github.com/d4k0/UniExtract2/releases/tag/v2.0.0-rc.1-30af0fb

**Comment by Darthagnon** [comment] 2018-05-17 22:41
Thank you :+1:

**Comment by d4k0** [comment] 2018-05-23 17:41
I updated it again:

https://github.com/d4k0/UniExtract2/releases/tag/v2.0.0-rc.1-f1177e7

**Comment by BravoOneCharlie** [comment] 2018-06-21 04:32
How come Bioruebe hasn't been adding new releases?

**Comment by d4k0** [comment] 2018-06-23 20:05
New update:

https://github.com/d4k0/UniExtract2/releases/tag/v2.0.0-rc.1-8ad1266

**Comment by gvp9000** [comment] 2018-06-24 12:16
here is the x64 version

https://www.dropbox.com/s/3jufhpvu3wqg5wn/UniExtract_8ad1266.zip?dl=0

**Comment by BravoOneCharlie** [comment] 2018-06-25 03:09
Unfortunately, I've downloaded every one I've and they all say "Please select a valid file." everytime I do a batch extract. It does extract them, but having that pop up every time first is really annoying. Also, I am curious specifically about why Bioruebe has stopped adding new releases.
![untitled](https://user-images.githubusercontent.com/33834742/41828504-748c5c60-77ea-11e8-9e0f-0669e9e2940d.png)

**Comment by BravoOneCharlie** [comment] 2018-07-03 23:14
I don't mean to sound like I'm complaining, I do really appreciate you compiling the new versions for us.

**Comment by d4k0** [comment] 2018-07-06 23:06
Do you mean me? Well, I just use AutoIt to compile the program, so the problem should be in the code. Is it working with the last final version? I haven't used the batch mode yet, so I can't comment on this.

Bioruebe is still working on this project (as can be seen by looking at the commits), but there are probably some more bugs to fix before releasing a RC.

**Comment by BravoOneCharlie** [comment] 2018-07-07 09:52
I know the issue is in the code and not anything to do with compiling it. I just wanted to make it clear that I do appreciate you compiling it for us.

**Comment by Bioruebe** [comment] 2018-07-28 02:21
> all say "Please select a valid file." everytime I do a batch extract

Thanks for reporting the bug, I fixed it in the last commit. Use the built-in updater of d4k0's RC 1 builds to get the latest version. (At least I hope this works correctly; I'm still working on fixing bugs in the new updater. This is also one of the main reasons no new releases are available. I *really* don't want to break the updater for all users...)

**Comment by BravoOneCharlie** [comment] 2018-07-28 06:09
> Use the built-in updater of d4k0's RC 1 builds to get the latest version.

The update did work, but the first update it found would say something about an invalid package being passed to the updater when I tried to install it. I said no to that update and then it found another update that did work correctly. Thank you for your hard work on UniExtract2, it's one of my favorite programs!

**Comment by BravoOneCharlie** [comment] 2018-07-28 06:14
I gguess that wasn't the most current update, there was another update when I checked, but after updating again the "please select a valid file." bug is fixed!

**Comment by d4k0** [comment] 2018-07-28 22:07
I updated to the latest version:

https://github.com/d4k0/UniExtract2/releases/tag/v2.0.0-rc.1-5227ea2

I just tested the new updater and it finally seems to be able to update ffmpeg without an error.

When you updated to the latest version, answer the first update message with "No" (this is the ffmpeg update) and the second one with "Yes" (this is the UniExtract update). It will then update a few files (like the updater and somehow even `UniExtract.exe`). On the next start the ffmpeg update should now work, at least it worked for me.

**Comment by Bioruebe** [comment] 2018-08-03 03:42
@BravoOneCharlie I'm glad it worked. The updater still had some bugs a few days ago, the 'invalid package' is gone now.

Closing this issue as RC1 has been released.

For everone using one of the builds linked in this thread, it might be possible that the update fails due to some bugs present in the old versions. Simply download the current [UniExtract.exe](https://update.bioruebe.com/uniextract/data/UniExtract.exe) and replace your old file. Then use the build-in 'Check for updates'. If it still does not work, try running UniExtract as administrator.

**Closed by Bioruebe** 2018-08-03 03:42 UTC
